# Generated by Django 3.1 on 2020-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='men',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='women',
            field=models.BooleanField(default=False),
        ),
    ]
